# Generated by Django 4.2.2 on 2023-06-21 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmacy',
            old_name='distance',
            new_name='kilometer',
        ),
    ]
