# Generated by Django 4.2.2 on 2023-07-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_distance_pharmacy_kilometer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='pharmacy',
            new_name='pharmacies',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='number_in_stock',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='pharmacy',
            old_name='kilometer',
            new_name='distance',
        ),
        migrations.AlterField(
            model_name='medicine',
            name='price',
            field=models.FloatField(),
        ),
    ]
